

```python
import os
os.listdir()
```




    ['2020-04-17-tweet.ipynb',
     '.DS_Store',
     '2020-04-08-trial-fastpages.ipynb',
     'code.ipynb',
     'test.csv',
     'README.md',
     '2020-02-20-test.ipynb',
     'train.csv',
     '.ipynb_checkpoints',
     'my_icons']




```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
```


```python
12.47
```




    12.47



# Data


>Twitter has become an important communication channel in times of emergency.
The ubiquitousness of smartphones enables people to announce an emergency theyâ€™re observing in real-time. Because of this, more agencies are interested in programatically monitoring Twitter (i.e. disaster relief organizations and news agencies). Soure: https://www.kaggle.com/c/nlp-getting-started/overview


```python
df = pd.read_csv('train.csv')
```


```python
df.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>keyword</th>
      <th>location</th>
      <th>text</th>
      <th>target</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Our Deeds are the Reason of this #earthquake M...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>4</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Forest fire near La Ronge Sask. Canada</td>
      <td>1</td>
    </tr>
    <tr>
      <td>2</td>
      <td>5</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>All residents asked to 'shelter in place' are ...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>3</td>
      <td>6</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>13,000 people receive #wildfires evacuation or...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>4</td>
      <td>7</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Just got sent this photo from Ruby #Alaska as ...</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>




```python
df['target'].value_counts()
```




    0    4342
    1    3271
    Name: target, dtype: int64




```python
sns.barplot(x=['Normal Tweet', 'Disaster Tweet'],
           y=df['target'].value_counts().values)
plt.title('Tweet Distribution')
```




    Text(0.5, 1.0, 'Tweet Distribution')




![png](output_7_1.png)


# Model


```python
from fastai2.text.all import *
from nbdev.showdoc import *
```


    ---------------------------------------------------------------------------

    ModuleNotFoundError                       Traceback (most recent call last)

    <ipython-input-62-5ca7fe234680> in <module>
    ----> 1 from fastai2.text.all import *
          2 from nbdev.showdoc import *


    ModuleNotFoundError: No module named 'fastai2'



```python
path = Path()
path.ls()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-63-88e21b776b5f> in <module>
    ----> 1 path = Path()
          2 path.ls()


    NameError: name 'Path' is not defined



```python
df.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>keyword</th>
      <th>location</th>
      <th>text</th>
      <th>target</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Our Deeds are the Reason of this #earthquake M...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>4</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Forest fire near La Ronge Sask. Canada</td>
      <td>1</td>
    </tr>
    <tr>
      <td>2</td>
      <td>5</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>All residents asked to 'shelter in place' are ...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>3</td>
      <td>6</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>13,000 people receive #wildfires evacuation or...</td>
      <td>1</td>
    </tr>
    <tr>
      <td>4</td>
      <td>7</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Just got sent this photo from Ruby #Alaska as ...</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>




```python
df.shape
```




    (7613, 5)



Let's shuffle the data and set 20% of the data for model validation


```python
df = df.sample(frac=1).reset_index(drop=True)
```


```python
len(df) *0.8
```




    6090.400000000001




```python
df['is_valid'] = False
```


```python
df.loc[:int(len(df)*0.8),'is_valid'] = True
```


```python
df['is_valid'].value_counts()
```




    True     6091
    False    1522
    Name: is_valid, dtype: int64




```python
df['text'][5000]
```




    'Refugio oil spill may have been costlier bigger than projected http://t.co/zdtcw9Fsx1'




```python
dbunch_lm = TextDataLoaders.from_df(df, text_col='text', 
                                    label_col='target', 
                                    path=path, is_lm=True,
                                    valid_col='is_valid')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-72-6c34e45a6289> in <module>
    ----> 1 dbunch_lm = TextDataLoaders.from_df(df, text_col='text', 
          2                                     label_col='target',
          3                                     path=path, is_lm=True,
          4                                     valid_col='is_valid')


    NameError: name 'TextDataLoaders' is not defined



```python
dbunch_lm.train_ds[0]
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-73-29276bc2ebce> in <module>
    ----> 1 dbunch_lm.train_ds[0]
    

    NameError: name 'dbunch_lm' is not defined



```python
dbunch_lm.vocab[:20]
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-74-c0f83e7b9f9b> in <module>
    ----> 1 dbunch_lm.vocab[:20]
    

    NameError: name 'dbunch_lm' is not defined



```python
dbunch_lm.show_batch()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-75-c51636f720be> in <module>
    ----> 1 dbunch_lm.show_batch()
    

    NameError: name 'dbunch_lm' is not defined


# Language model


```python
bs = 32
```


```python
path.ls()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-77-4e20bcf9cc48> in <module>
    ----> 1 path.ls()
    

    NameError: name 'path' is not defined



```python
len(dbunch_lm.vocab)
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-78-3ddbb33b83a6> in <module>
    ----> 1 len(dbunch_lm.vocab)
    

    NameError: name 'dbunch_lm' is not defined



```python
learn = language_model_learner(dbunch_lm, AWD_LSTM, drop_mult=0.3, 
                               metrics=[accuracy, Perplexity()]).to_fp16()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-79-05e880bca9a8> in <module>
    ----> 1 learn = language_model_learner(dbunch_lm, AWD_LSTM, drop_mult=0.3, 
          2                                metrics=[accuracy, Perplexity()]).to_fp16()


    NameError: name 'language_model_learner' is not defined



```python
learn.lr_find()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-80-d81c6bd29d71> in <module>
    ----> 1 learn.lr_find()
    

    NameError: name 'learn' is not defined



```python
learn.fit_one_cycle(1, 1e-2, moms=(0.8,0.7,0.8))
```


```python
learn.save('fit_head')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-81-2cfc6c464230> in <module>
    ----> 1 learn.save('fit_head')
    

    NameError: name 'learn' is not defined



```python
learn.load('fit_head');
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-82-1ff90cae0b4c> in <module>
    ----> 1 learn.load('fit_head');
    

    NameError: name 'learn' is not defined



```python
learn.unfreeze()
```


```python
learn.fit_one_cycle(10, 2e-2, moms=(0.8,0.7,0.8))
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-83-6ab537c0c31b> in <module>
    ----> 1 learn.fit_one_cycle(10, 2e-2, moms=(0.8,0.7,0.8))
    

    NameError: name 'learn' is not defined



```python
learn.save('fine_tuned')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-84-d06ce8c549d2> in <module>
    ----> 1 learn.save('fine_tuned')
    

    NameError: name 'learn' is not defined



```python
learn.load('fine_tuned');
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-85-44585e99aeed> in <module>
    ----> 1 learn.load('fine_tuned');
    

    NameError: name 'learn' is not defined



```python
TEXT = 'Car accidents'
N_WORDS = 30
N_SENTENCES = 2
```


```python
print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-86-135dd315cd3b> in <module>
    ----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))
    

    <ipython-input-86-135dd315cd3b> in <genexpr>(.0)
    ----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))
    

    NameError: name 'learn' is not defined



```python
learn.save_encoder('fine_tuned_enc')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-87-2eaedba51eb4> in <module>
    ----> 1 learn.save_encoder('fine_tuned_enc')
    

    NameError: name 'learn' is not defined


# Classifier


```python
tweet_class = DataBlock(blocks=(TextBlock.from_df('text',vocab=dbunch_lm.vocab),CategoryBlock),
                       get_y = ColReader('target'),
                       get_x = ColReader('text'),
                       splitter=ColSplitter())
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-88-25cae671d553> in <module>
    ----> 1 tweet_class = DataBlock(blocks=(TextBlock.from_df('text',vocab=dbunch_lm.vocab),CategoryBlock),
          2                        get_y = ColReader('target'),
          3                        get_x = ColReader('text'),
          4                        splitter=ColSplitter())


    NameError: name 'DataBlock' is not defined



```python
df.head(2)
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>keyword</th>
      <th>location</th>
      <th>text</th>
      <th>target</th>
      <th>is_valid</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>7183</td>
      <td>mudslide</td>
      <td>London, England</td>
      <td>@new_hart2010 #mudslide... nuff said #GBBO</td>
      <td>1</td>
      <td>True</td>
    </tr>
    <tr>
      <td>1</td>
      <td>8110</td>
      <td>rescued</td>
      <td>Jammu | Kashmir | Delhi</td>
      <td>18 bovines rescued 3 smugglersÃ¥ÃŠnabbed http://...</td>
      <td>1</td>
      <td>True</td>
    </tr>
  </tbody>
</table>
</div>




```python
pd.crosstab(df['is_valid'],df['target'])
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>target</th>
      <th>0</th>
      <th>1</th>
    </tr>
    <tr>
      <th>is_valid</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>False</td>
      <td>856</td>
      <td>666</td>
    </tr>
    <tr>
      <td>True</td>
      <td>3486</td>
      <td>2605</td>
    </tr>
  </tbody>
</table>
</div>




```python
dbunch_class = tweet_class.dataloaders(df,path, bs=bs, seq_len=80)
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-91-f8069766aa6d> in <module>
    ----> 1 dbunch_class = tweet_class.dataloaders(df,path, bs=bs, seq_len=80)
    

    NameError: name 'tweet_class' is not defined



```python
dbunch_class.show_batch()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-92-0d2390b12d74> in <module>
    ----> 1 dbunch_class.show_batch()
    

    NameError: name 'dbunch_class' is not defined



```python
learn = text_classifier_learner(dbunch_class, AWD_LSTM,
                                drop_mult=0.3, metrics=accuracy).to_fp16()
learn.load_encoder('fine_tuned_enc')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-93-8f8ee2c94a49> in <module>
    ----> 1 learn = text_classifier_learner(dbunch_class, AWD_LSTM,
          2                                 drop_mult=0.3, metrics=accuracy).to_fp16()
          3 learn.load_encoder('fine_tuned_enc')


    NameError: name 'text_classifier_learner' is not defined



```python
learn.lr_find()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-94-d81c6bd29d71> in <module>
    ----> 1 learn.lr_find()
    

    NameError: name 'learn' is not defined



```python
learn.fit_one_cycle(1, 1e-2, moms=(0.8,0.7, 0.8))
```


```python
learn.save('first')
learn.load('first')
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-95-94e0399fd504> in <module>
    ----> 1 learn.save('first')
          2 learn.load('first')


    NameError: name 'learn' is not defined



```python
learn.freeze_to(-2)
learn.fit_one_cycle(5, slice(1e-2/(2.6**4),1e-2), moms=(0.8,0.7, 0.8))
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-96-a5639c873429> in <module>
    ----> 1 learn.freeze_to(-2)
          2 learn.fit_one_cycle(5, slice(1e-2/(2.6**4),1e-2), moms=(0.8,0.7, 0.8))


    NameError: name 'learn' is not defined



```python
learn.freeze_to(-3)
learn.fit_one_cycle(1, slice(5e-3/(2.6**4),5e-3),moms=(0.8,0.7, 0.8))
```


```python
learn.unfreeze()
learn.fit_one_cycle(2, slice(1e-3/(2.6**4),1e-3), moms=(0.8,0.7, 0.8))
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-97-d9652e467fa8> in <module>
    ----> 1 learn.unfreeze()
          2 learn.fit_one_cycle(2, slice(1e-3/(2.6**4),1e-3), moms=(0.8,0.7, 0.8))


    NameError: name 'learn' is not defined



```python
learn.fit_one_cycle(4,slice(1e-3/(2.6**4),1e-3), moms=(0.8,0.7, 0.8))
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-98-54c844593fc0> in <module>
    ----> 1 learn.fit_one_cycle(4,slice(1e-3/(2.6**4),1e-3), moms=(0.8,0.7, 0.8))
    

    NameError: name 'learn' is not defined



```python
learn.predict("there's a fire emergency in my city")
```


```python
learn.predict("What a peaceful place to live")
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-99-2dda88c06e0a> in <module>
    ----> 1 learn.predict("What a peaceful place to live")
    

    NameError: name 'learn' is not defined



```python
learn.show_results()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-100-c3b657dcc9ae> in <module>
    ----> 1 learn.show_results()
    

    NameError: name 'learn' is not defined


# Interpretation


```python
from fastai.text.interpret import *
```


```python
interp = ClassificationInterpretation.from_learner(learn)
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-102-aa7f7b70a42b> in <module>
    ----> 1 interp = ClassificationInterpretation.from_learner(learn)
    

    NameError: name 'ClassificationInterpretation' is not defined



```python
interp.confusion_matrix()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-103-f05b1019acb7> in <module>
    ----> 1 interp.confusion_matrix()
    

    NameError: name 'interp' is not defined



```python
interp.plot_top_losses(5)
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-104-76c31c34351e> in <module>
    ----> 1 interp.plot_top_losses(5)
    

    NameError: name 'interp' is not defined



```python
interp.plot_confusion_matrix()
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-105-ab4f144f3c10> in <module>
    ----> 1 interp.plot_confusion_matrix()
    

    NameError: name 'interp' is not defined



```python

```


```python

```


```python

```


```python

```


```python

```


```python

```
